# Generated by Django 6.0.2 on 2026-02-24 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='tipo_ranking',
            field=models.CharField(choices=[('kills', 'Ranking por Kills'), ('wins_goals', 'Ranking por Victorias y Goles')], default='kills', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='juego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.juego'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(blank=True, choices=[('AM', 'Amateur'), ('NO', 'Normal'), ('EX', 'Expert')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('partidos_ganados', models.IntegerField(default=0)),
                ('goles', models.IntegerField(default=0)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.juego')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('jugador', 'juego')},
            },
        ),
    ]
